### ISSUE TITLE
Verifying contract is failing on rinkeby network

### ISSUE THREAD

**Issue by hecomp** [hashlips-lab/nft-erc721-collection#56]
`Error in plugin @nomiclabs/hardhat-etherscan: The contract verification failed.
Reason: Fail - Unable to verify

For more info run Hardhat with --show-stack-traces
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.`

**Comment by h0rizons** [comment]
I'm also getting the same issue using the most recent pull.

[Error - 9:40:12 PM] solc error: TypeError: solc.compileStandardWrapper is not a function
[Error - 9:40:12 PM] solc error: TypeError: solc.compileStandardWrapper is not a function

I had everything verifying perfectly on the version from around a week ago.

**Comment by h0rizons** [comment]
I just downloaded the v1.0.1 that had initially been working for me, followed every step to the T, and I'm getting the verification failure on this build as well.

**Comment by hecomp** [comment]
Yeah same here @h0rizons. Yesterday was flawless but today not so much everything else works minting, WL, Presale, Public Sale, reveal. I don't know if is rinkeby restriction for verification.

**Comment by liarco** [comment]
Hi @hecomp and @h0rizons,
thank you for letting me know about this, it might be related to https://github.com/NomicFoundation/hardhat/issues/2437.

Can you please run the following command inside the `/smart-contract` folder and try again?
```bash
> yarn upgrade @nomiclabs/hardhat-etherscan
```

If this solves the issue we are gonna update the dependency and push a new commit to `main`. Thank you!

**Comment by liarco** [comment]
Sorry, I forgot to mention that you should also update the version number in the `/smart-contract/package.json` file before running `yarn upgrade ...`:
```json
    "@nomiclabs/hardhat-etherscan": "^3.0.3",
```

**Comment by cptlchad** [comment]
Was a problem on etherscan and is fixed now

**Comment by hecomp** [comment]
@liarco @cptlchad I've tried and is working fine again. Thanks for the support and fix.

**Comment by liarco** [comment]
Thank you guys, gonna close this but feel free to open a new issue if anything strange happens again! 😉

**Comment by h0rizons** [comment]
Hmm I'm still getting the error. I got it to successfully verify last night, and I tried again today with a new contract and I'm getting the error again. I tried your suggestions and got everything updated successfully, but it still isn't working. Thanks for your help - really appreciate it.

`Error in plugin @nomiclabs/hardhat-etherscan: The contract verification failed.
Reason: Fail - Unable to verify`

**Comment by liarco** [comment]
Hi @h0rizons,
unfortunately we are all on the same boat. I'm busy testing #29 before merging it but I can't get my testing contracts to verify properly. It seems like the issue is on Etherscan side since other projects report the same thing and this happens without any change on our side: https://github.com/NomicFoundation/hardhat/issues/2447

I'm afraid we just have to wait... 😞

**Comment by h0rizons** [comment]
Sorry @liarco, I saw your earlier comment and thought that it was sorted.

So none of the versions will verify on rinkeby right now?

**Comment by liarco** [comment]
@h0rizons it was working until a few hours ago, but it might be Etherscan's fault here. The verification service is not working properly and chances are:
1. Something is broken on Etherscan's side so they have to fix that
2. The Hardhat library might need to be updated in order to fix this but as you can see from the issue I mentioned above they claim there is nothing wrong on their side and people should contact Etherscan

At the moment I got reports from users failing to verify on Rinkeby, not the Mainnet. But I haven't had the chance to test the Mainnet myself.

**Comment by h0rizons** [comment]
I'm getting an error on deployment now even, is this related to the same issue?

`$ hardhat run scripts/1_deploy.ts --network rinkeby
No need to generate any newer typings.
ProviderError: request failed or timed out
    at HttpProvider.request (/Users/timemachine/Desktop/easyc/smart-contract/node_modules/hardhat/src/internal/core/providers/http.ts:49:19)
    at LocalAccountsProvider.request (/Users/timemachine/Desktop/easyc/smart-contract/node_modules/hardhat/src/internal/core/providers/accounts.ts:187:34)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async AutomaticGasPriceProvider._suggestEip1559FeePriceValues (/Users/timemachine/Desktop/easyc/smart-contract/node_modules/hardhat/src/internal/core/providers/gas-providers.ts:233:22)
    at async AutomaticGasPriceProvider.request (/Users/timemachine/Desktop/easyc/smart-contract/node_modules/hardhat/src/internal/core/providers/gas-providers.ts:174:34)
    at async EthersProviderWrapper.send (/Users/timemachine/Desktop/easyc/smart-contract/node_modules/@nomiclabs/hardhat-ethers/src/internal/ethers-provider-wrapper.ts:13:20)
error Command failed with exit code 1.`

**Comment by liarco** [comment]
@h0rizons everything is working again on my side (nothing changed) so I think this has nothing to do with our code, nor the library. It's probably something wrong with Etherscan.

**Comment by hamhocks** [comment]
I'm having the same problem plugin error but can't figure out if its hardhat or etherscan.

**Comment by liarco** [comment]
@hamhocks it's a known issue these days, the Hardhat team states it's not their fault (and it sounds possible since verification fails/succeeds randomly without any change in the code), so Etherscan seems to be the culprit here.

Here are some references to relevant issues:
- https://github.com/NomicFoundation/hardhat/issues/2447
- https://github.com/NomicFoundation/hardhat/issues/2448
- https://github.com/NomicFoundation/hardhat/issues/2465

Anyway this seems not related to our code specifically.
